const fileAssociations = {
	"JavaScript": [".js", ".mjs", ".cjs"],
	"TypeScript": [".ts", ".tsx", ".d.ts"],
	"Python": [".py", ".pyw"],
	"Java": [".java", ".jar"],
	"C": [".c", ".h"],
	"C++": [".cpp", ".cc", ".cxx", ".hpp", ".hxx", ".h"],
	"C#": [".cs"],
	"Go": [".go"],
	"Rust": [".rs"],
	"Ruby": [".rb", ".erb"],
	"PHP": [".php", ".phtml", ".php3", ".php4", ".php5", ".phps"],
	"Swift": [".swift"],
	"Kotlin": [".kt", ".kts"],
	"Dart": [".dart"],
	"Scala": [".scala", ".sc"],
	"Perl": [".pl", ".pm", ".t"],
	"R": [".r", ".R", ".Rmd"],
	"Shell": [".sh", ".bash", ".zsh"],
	"PowerShell": [".ps1", ".psm1", ".psd1"],
	"HTML": [".html", ".htm"],
	"CSS": [".css"],
	"Sass/SCSS": [".sass", ".scss"],
	"JSON": [".json"],
	"YAML": [".yaml", ".yml"],
	"XML": [".xml", ".xsd", ".xslt"],
	"SQL": [".sql"],
	"Markdown": [".md", ".markdown"],
	"Makefile": ["Makefile", "makefile"],
	"Dockerfile": ["Dockerfile"],
	"Batch": [".bat", ".cmd"],
	"Lua": [".lua"],
	"Haskell": [".hs", ".lhs"],
	"Elixir": [".ex", ".exs"],
	"Erlang": [".erl", ".hrl"],
	"Assembly": [".asm", ".s", ".S"],
	"MATLAB": [".m"],
	"Vim Script": [".vim"],
	"TeX/LaTeX": [".tex", ".ltx", ".sty"],
	"Groovy": [".groovy", ".gvy", ".gy", ".gsh"],
	"Objective-C": [".m", ".mm", ".h"],
	"F#": [".fs", ".fsi", ".fsx", ".fsscript"],
	"Visual Basic": [".vb"],
	"COBOL": [".cob", ".cbl"],
	"Fortran": [".f", ".for", ".f90", ".f95"],
	"Prolog": [".pl", ".pro"],
	"Tcl": [".tcl"],
	"Nim": [".nim", ".nims", ".nimble"],
	"Crystal": [".cr"],
	"V": [".v"],
	"Zig": [".zig"],
	"ReScript": [".res", ".resi"],
	"ReasonML": [".re", ".rei"],
	"Racket": [".rkt"],
	"Common Lisp": [".lisp", ".lsp", ".cl"],
	"Scheme": [".scm", ".ss"],
	"Julia": [".jl"],
};

export function get_language_by_extension(extension: string): string | undefined {
	for (const [language, extensions] of Object.entries(fileAssociations)) {
		if (extensions.includes(extension)) {
			return language;
		}
	}
	return undefined;
}
